export const environment = {
  production: false,
  dev: {
    base_url: 'https://dev.inge.mpdl.mpg.de',
    elastic_url: '/inge',
    rest_url: '/rest',
    rest_users: '/users',
    rest_ous: '/ous',
    rest_contexts: '/contexts',
    rest_items: '/items',
    item_index_name: 'new_model_items',
    item_index_type: 'item',
    user_index_name: 'new_model_users',
    user_index_type: 'user',
    ou_index_name: 'new_model_ous',
    ou_index_type: 'organization',
    ctx_index_name: 'new_model_contexts',
    ctx_index_type: 'context',
  },
  elastic_admin: 'wilhelm',
};
